### ISSUE TITLE
请问wxpython是不是不可以再linux下用啊？我在kali和parrot中装wxpython的时候都是一片爆红，wind倒是正常

### ISSUE THREAD

**Issue by Joackk** [ghealer/GUI_Tools#13]
![image](https://user-images.githubusercontent.com/45162558/135721759-b386ae07-bc8e-4417-a694-a6e847a94246.png)

**Comment by ghealer** [comment]
![image](https://user-images.githubusercontent.com/23149905/136484095-cc5b3caa-3087-4261-9dbe-a4824b060f23.png)

**Comment by ghealer** [comment]
看一下官网的介绍
https://wxpython.org/pages/downloads/index.html
