### ISSUE TITLE
打开后无论点击什么按钮都没有反应

### ISSUE THREAD

**Issue by dreamsky119** [ghealer/GUI_Tools#2]
打开后无论点击什么按钮都没有反应，每点一次cmd窗口提示“系统找不到指定的路径”

**Comment by ghealer** [comment]
1、检查工具包是否下载完成
2、检查本机工具目录环境是否和目录结构一样
3、将 GUI_Tools V1.0 目录修改为 GUI_Tools
4、最好能将运行截图发出来

**Comment by Nowlang** [comment]
工具包怎么下载？

**Comment by dreamsky119** [comment]
解决了，目录结构放错了，谢谢大佬
