### ISSUE TITLE
releases下载到的文件与readme描述的不匹配

### ISSUE THREAD

**Issue by mbx119** [ghealer/GUI_Tools#20]
下载到的文件
![image](https://user-images.githubusercontent.com/57660634/173475162-f0f55fbd-a64f-4596-af05-34c8811e747e.png)
readme描述的目录结构
![image](https://user-images.githubusercontent.com/57660634/173475285-b48aa4da-6e63-454a-927c-98b8d117ad66.png)
缺少工具包，作者帮忙确认一下问题

**Comment by ghealer** [comment]
README.md好好看你就知道问题了

**Comment by mbx119** [comment]
base64我直呼好家伙

发自我的iPhone
