### ISSUE TITLE
启动GUI_Tools后报错，点击哥斯拉、Yakit也报错。

### ISSUE THREAD

**Issue by yb2233** [ghealer/GUI_Tools#22]
<img width="345" alt="微信截图_20220616110129" src="https://user-images.githubusercontent.com/99227913/173982136-6b327fcc-ff8f-4651-bdd5-0838ce4166a8.png">
操作系统 win7 64位旗舰版
python3.8
Java 版本1.8.0_201

**Comment by ghealer** [comment]
这是别人拿GUI_Tools改的，我不清楚，找那个改的人
